### ISSUE TITLE
TypeError on accessing ManufacturerListView or DeviceTypeListView under Nautobot 1.3

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-plugin-welcome-wizard#56]
### Environment
* Python version:  
* Nautobot version:  1.3.8
* nautobot-welcome-wizard version:  1.1.0

### Expected Behavior

ManufacturerListView and DeviceTypeListView to load successfully

### Observed Behavior

Page access raises a TypeError:

```
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/utilities/views.py", line 114, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/welcome_wizard/views.py", line 68, in get
    return super().get(request, *args, **kwargs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/views/generic.py", line 276, in get
    valid_actions = self.validate_action_buttons(request)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/views/generic.py", line 196, in validate_action_buttons
    for action in self.action_buttons:
Exception Type: TypeError at /plugins/welcome_wizard/manufacturers/
Exception Value: 'NoneType' object is not iterable
```

The issue appears to be that these views declare `action_buttons = None` but Nautobot core is expecting these to be iterables, i.e. `[]` or `()`. The validation of this expectation was added in https://github.com/nautobot/nautobot/pull/1806 so this probably was passing in earlier Nautobot releases.

I will also open an issue against Nautobot core to not error out in this check when `action_buttons` is `None`.

**Comment by glennmatthews** [comment]
See also https://github.com/nautobot/nautobot/issues/2107

**Comment by jvanderaa** [comment]
Also in Nautobot 1.4
