### ISSUE TITLE
Welcome Wizard does not install on Nautobot v2.x.x

### ISSUE THREAD

**Issue by NetworkingB2A** [nautobot/nautobot-plugin-welcome-wizard#80]
### Environment
* Python version:  3.8
* Nautobot version:  V2.0.1
* nautobot-welcome-wizard version:  V1.1.4

### Side Note
After talking with Nautobot team, the issue is because Sites and Regions are changing to Locations in V2.x.x. This Issue is to track the update.

### Expected Behavior
I expected the app would install while running the post_upgrade script

### Observed Behavior
The app did not install and and error was thrown.

### Steps to Reproduce
1. Install app according to normal install procedure.
2. pip install welcome_wizard
3. Add to nautobot.py file.
4. Run post_upgrade script.

### Debugging results

```
[nautobot@nautobot-server ~]$ nautobot-server post_upgrade
Traceback (most recent call last):
  File "/home/nautobot/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/home/nautobot/lib64/python3.8/site-packages/nautobot/core/cli/__init__.py", line 54, in main
    run_app(
  File "/home/nautobot/lib64/python3.8/site-packages/nautobot/core/runner/runner.py", line 297, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/home/nautobot/lib64/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/nautobot/lib64/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/home/nautobot/lib64/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nautobot/lib64/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/nautobot/lib64/python3.8/site-packages/nautobot/core/apps/__init__.py", line 848, in ready
    super().ready()
  File "/home/nautobot/lib64/python3.8/site-packages/nautobot/core/apps/__init__.py", line 71, in ready
    registry["new_ui_ready_routes"].update(get_all_new_ui_ready_routes())
  File "/home/nautobot/lib64/python3.8/site-packages/nautobot/core/utils/navigation.py", line 47, in get_all_new_ui_ready_routes
    url_patterns = resolver.url_patterns
  File "/home/nautobot/lib64/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nautobot/lib64/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/nautobot/lib64/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nautobot/lib64/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nautobot/lib64/python3.8/site-packages/nautobot/core/urls.py", line 7, in <module>
    from nautobot.extras.plugins.urls import (
  File "/home/nautobot/lib64/python3.8/site-packages/nautobot/extras/plugins/urls.py", line 32, in <module>
    urlpatterns = import_object(f"{plugin_path}.urls.urlpatterns")
  File "/home/nautobot/lib64/python3.8/site-packages/nautobot/extras/plugins/utils.py", line 46, in import_object
    spec.loader.exec_module(module)
  File "/home/nautobot/lib64/python3.8/site-packages/welcome_wizard/urls.py", line 6, in <module>
    from . import views
  File "/home/nautobot/lib64/python3.8/site-packages/welcome_wizard/views.py", line 13, in <module>
    from nautobot.dcim.models import Site, DeviceType, Manufacturer
ImportError: cannot import name 'Site' from 'nautobot.dcim.models' (/home/nautobot/lib64/python3.8/site-packages/nautobot/dcim/models/__init__.py)
```

**Comment by analyticalhybrid** [comment]
Have the same issue.

`
Traceback (most recent call last):
  File "/opt/nautobot/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/cli/__init__.py", line 54, in main
    run_app(
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/runner/runner.py", line 297, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/nautobot/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/opt/nautobot/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/nautobot/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/apps/__init__.py", line 848, in ready
    super().ready()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/apps/__init__.py", line 71, in ready
    registry["new_ui_ready_routes"].update(get_all_new_ui_ready_routes())
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/utils/navigation.py", line 47, in get_all_new_ui_ready_routes
    url_patterns = resolver.url_patterns
  File "/opt/nautobot/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/nautobot/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/nautobot/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/nautobot/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/urls.py", line 7, in <module>
    from nautobot.extras.plugins.urls import (
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/plugins/urls.py", line 32, in <module>
    urlpatterns = import_object(f"{plugin_path}.urls.urlpatterns")
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/extras/plugins/utils.py", line 46, in import_object
    spec.loader.exec_module(module)
  File "/opt/nautobot/lib/python3.8/site-packages/welcome_wizard/urls.py", line 6, in <module>
    from . import views
  File "/opt/nautobot/lib/python3.8/site-packages/welcome_wizard/views.py", line 13, in <module>
    from nautobot.dcim.models import Site, DeviceType, Manufacturer
ImportError: cannot import name 'Site' from 'nautobot.dcim.models' (/opt/nautobot/lib/python3.8/site-packages/nautobot/dcim/models/__init__.py)
`

**Comment by analyticalhybrid** [comment]
This is working now and probably should be closed, @NetworkingB2A .

**Comment by NetworkingB2A** [comment]
I will test it out this week and make sure its working for me. thank you.

**Comment by analyticalhybrid** [comment]
One thing of note: the import device type option didn't start working for me until just about 15 minutes ago or so. The git job had ran several times, but the table never populated. Maybe it was an issue with the data from git repo, but appears to be good now.
